### ISSUE TITLE
你好，我在angular教程的页面上碰到了以下错误，请帮忙看看

### ISSUE THREAD

**Issue by youling4438** [ng-docs/www.angular.cn#1]
### 非常感谢你们翻译并同步angular.dev到angular.cn。

近期我碰到了以下错误，请帮忙看看是什么原因导致的？

截图：
![image](https://github.com/user-attachments/assets/bf58a565-841a-4a33-9cb7-dc4aa813658b)

具体的error:
```
added 404 packages in 13s
 
66 packages are looking for funding
  run `npm fund` for details
 
> angular.dev@0.0.0 start
> NG_BUILD_PARALLEL_TS=0 ng serve
 
Prebundling has been configured but will not be used because caching has been disabled.
Prebundling has been configured but will not be used because caching has been disabled.
Application bundle generation failed. [18.733 seconds]
 
✘ [ERROR] Unable to deserialize cloned data. [plugin angular-sass]
 
  This error came from the "onLoad" callback registered here:
 
    node_modules/@angular/build/src/tools/esbuild/stylesheets/stylesheet-plugin-factory.js:145:22:
      145 │                 build.onLoad({ filter: language.componentFilter, ...
          ╵                       ~~~~~~
 
    at setup (/home/httpswwwangularcn-ong4/node_modules/@angular/build/src/tools/esbuild/stylesheets/stylesheet-plugin-factory.js:145:23)
    at handlePlugins (/home/httpswwwangularcn-ong4/node_modules/esbuild/lib/main.js:1138:21)
    at buildOrContextImpl (/home/httpswwwangularcn-ong4/node_modules/esbuild/lib/main.js:863:5)
    at Object.buildOrContext (/home/httpswwwangularcn-ong4/node_modules/esbuild/lib/main.js:689:5)
    at eval (/home/httpswwwangularcn-ong4/node_modules/esbuild/lib/main.js:1828:68)
    at Object.context (/home/httpswwwangularcn-ong4/node_modules/esbuild/lib/main.js:1828:27)
    at context (/home/httpswwwangularcn-ong4/node_modules/esbuild/lib/main.js:1670:58)
    at #performBundle (/home/httpswwwangularcn-ong4/node_modules/@angular/build/src/tools/esbuild/bundler-context.js:158:68)
 
 
Watch mode enabled. Watching for file changes...
```

**Comment by wszgrcy** [comment]
看样子是esbuild的插件问题?与源码无关,有相关链接吗

**Comment by youling4438** [comment]
> 看样子是esbuild的插件问题?与源码无关,有相关链接吗

直接打开官网就可以看到这个错误  https://www.angular.cn/tutorials/learn-angular/1-components-in-angular

**Comment by wszgrcy** [comment]
我和官方比较了下,同时试了下下载,也有问题,猜测可能是资源链接产生了问题,您如果不着急可以把`.cn`改为`.dev`,看原版的.

**Comment by youling4438** [comment]
> 我和官方比较了下,同时试了下下载,也有问题,猜测可能是资源链接产生了问题,您如果不着急可以把`.cn`改为`.dev`,看原版的.

好的，谢谢！
